use BD_CURSO_SSIS
go

--01 - cria a tabela
DROP TABLE IF EXISTS POPULACAO_MUNICIPIO
CREATE TABLE POPULACAO_MUNICIPIO
(
COD_UF CHAR(2),
COD_MUNICIPIO CHAR(5),
QTD_POPULACAO INT,
DATA_CARGA DATETIME
)

--02 - verifica os dados
SELECT * FROM POPULACAO_MUNICIPIO