use BD_CURSO_SSIS
go

--01 CRIA A TABELA UF REGIÃO
DROP TABLE IF EXISTS UF_REGIAO
create table UF_REGIAO
(
Unidade_federativa VARCHAR(50),
Sigla CHAR(2),
Regiao VARCHAR(50)
)


--02 CRIA A TABELA UF_REGIAO_QTD

DROP TABLE IF EXISTS UF_REGIAO_QTD
create table UF_REGIAO_QTD
(
Regiao VARCHAR(50),
Qtd_estado INT
)



--03 SELECIONANDO OS DADOS

SELECT * FROM UF_REGIAO

SELECT * FROM UF_REGIAO_QTD